spring.application.name=PracticaH2

# Configuración de la base de datos H2
spring.datasource.url=jdbc:h2:mem:onlineshop;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver

# H2: habilitar la consola
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Inicialización de SQL
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

# Logging detallado para depuración
logging.level.org.springframework.sql=DEBUG
logging.level.org.hibernate.SQL=DEBUG
